# fly.toml app configuration file generated for lia-brecho on 2025-10-09
app = "lia-brecho"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  DATA_DIR = "/data"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25

[[mounts]]
  source = "lia_data"
  destination = "/data"
