services:
  - type: web            # deve ser 'web'
    name: site-brecho
    env: static          # mantém 'static'
    branch: main
    buildCommand: ""     # nenhum build se for HTML/CSS/JS puro
    startCommand: ""     # nenhum start
    staticPublishPath: public # onde está o index.html neste projeto
    routes:
      - type: rewrite
        source: /admin
        destination: /admin.html
      - type: rewrite
        source: /login
        destination: /login.html
      - type: rewrite
        source: /owner
        destination: /owner.html
